version: '3.8'

services:
  pathway_app:
    build:
      context: .
      args:
        BUILD_ENVIRONMENT: dev
    environment:
      INPUT_CONNECTOR: python
      PATHWAY_THREADS: 1
    volumes:
      - .:/gaianet_rag_api_pipeline
    networks:
      - gaianet_rag_api_pipeline_network

  qdrant:
    image: qdrant/qdrant:v1.10.0
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_dev:/qdrant/storage:z
    networks:
      - gaianet_rag_api_pipeline_network

networks:
  gaianet_rag_api_pipeline_network:
    driver: bridge
